start  "" "C:\Program Files\Sublime Text 3\sublime_text.exe" "F:\manh-trinhquoc.github.io"
start  "" "C:\Program Files\Sublime Text 3\subl.exe" "F:\manh-trinhquoc.github.io\thang-long-tour\book-tour.html"
start  "" "C:\Program Files\Sublime Text 3\subl.exe" "F:\manh-trinhquoc.github.io\thang-long-tour\js\script.js"
start  "" "C:\Program Files\Sublime Text 3\subl.exe" "F:\manh-trinhquoc.github.io\thang-long-tour\scss\book-tour.scss"
start  "" "C:\Program Files\Sublime Text 3\subl.exe" "F:\manh-trinhquoc.github.io\thang-long-tour\scss\style.scss"